port: 4222
http_port: 8222
server_name: s2
jetstream {
    store_dir="/starfruit/cluster/s2"
}

cluster {
    name: c1
    port: 6222
    routes: [
        "nats-route://nats-hub-server-1:6222",
        "nats-route://nats-hub-server-2:6222",
        "nats-route://nats-hub-server-3:6222",
    ],
}

debug = true
trace = true