server_name: n3
port: 4222
http_port: 8222
cluster {
  name: "AUTH-POC"
  listen: 0.0.0.0:6222
  routes = [
    "nats://n1:6222",
    "nats://n2:6222"
  ]
}
operator: "/etc/nats/auth/operator/operator.jwt"
resolver: MEMORY
resolver_preload: {
  "AA5HJMKEUKT3RTIB27ETREVT6TTWVUAQFPLQNSJ76IK67WMFC2WDDWGO": "eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJTSVFGREJBTUxUTVRPNllYSlA1VVRHUUhON0dMSE1VWlRSVEdPTzI0WVhITFJZTkZLRVlRIiwiaWF0IjoxNzgyNDAxODQxLCJpc3MiOiJPQ0lYSElSSkpDTzVHTU9NV1lIQkY3RU0zWTJYNE5BWk5ENjJOUlJSQlpFV0lUUk9OWE4zUk9LTSIsIm5hbWUiOiJTRVJWSUNFQSIsInN1YiI6IkFBNUhKTUtFVUtUM1JUSUIyN0VUUkVWVDZUVFdWVUFRRlBMUU5TSjc2SUs2N1dNRkMyV0REV0dPIiwibmF0cyI6eyJsaW1pdHMiOnsic3VicyI6LTEsImRhdGEiOi0xLCJwYXlsb2FkIjotMSwiaW1wb3J0cyI6LTEsImV4cG9ydHMiOi0xLCJ3aWxkY2FyZHMiOnRydWUsImNvbm4iOi0xLCJsZWFmIjotMX0sImRlZmF1bHRfcGVybWlzc2lvbnMiOnsicHViIjp7fSwic3ViIjp7fX0sImF1dGhvcml6YXRpb24iOnt9LCJ0eXBlIjoiYWNjb3VudCIsInZlcnNpb24iOjJ9fQ.q0uwaa5VV79TJWtKBN5iprPNV-xFAYAvdvsyQen2xf8YzJ49aoBfS_-ZaeRfhPl3vMcJqZcSWwxJutmh1jidAQ"
}
