version: "3.5"

services:
  nats-server:
    image: nats:2.14
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats.conf:/etc/nats/nats.conf
      - jetstream-data:/starfruit/cluster
    command: "-c /etc/nats/nats.conf"

volumes:
  jetstream-data:
