port: 4222
http_port: 8222
jetstream {
    store_dir="/starfruit/cluster"
}

accounts {
    SYS: {
        users: [{user: admin, password: admin}]
    }
    STARFRUIT: {
        # Account JWT 또는 Account Public Key
        # nsc로 생성한 account의 public key
        # 예: AXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        # 또는 account JWT를 직접 임베드
        # account: "AB6TM54QB67Z3ES4IAJEBJDNR5YCUEKE6VQJHMJCU4LH53D5OUIDJXHM"
    }
}

system_account: SYS