port: 4222
http_port: 8222
server_name: jwt-runtime-poc
operator: "/etc/nats/auth/operator/operator.jwt"
resolver: MEMORY
resolver_preload: {
  "ADL5VIN2OZMNKYOWETDFHLKRILTZW4ZDKJPH5VVVLESCGRMOES4TSNQS": "eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJJQkpRTEsyUktVRUEyUzVYVkZYSFJOU1o0U1FMNDRXWFdYNjVFTTRCTjZHUVpVNkZNSFdRIiwiaWF0IjoxNzgyNDAwODcxLCJpc3MiOiJPQ09GNkRITEFDWUNZTFM2Vlk1N1hXUEtWRVFQVU1aN1lYTFlaQkZQRDJGM1czVzVUTzJWNVNHSiIsIm5hbWUiOiJTRVJWSUNFQSIsInN1YiI6IkFETDVWSU4yT1pNTktZT1dFVERGSExLUklMVFpXNFpES0pQSDVWVlZMRVNDR1JNT0VTNFRTTlFTIiwibmF0cyI6eyJsaW1pdHMiOnsic3VicyI6LTEsImRhdGEiOi0xLCJwYXlsb2FkIjotMSwiaW1wb3J0cyI6LTEsImV4cG9ydHMiOi0xLCJ3aWxkY2FyZHMiOnRydWUsImNvbm4iOi0xLCJsZWFmIjotMX0sImRlZmF1bHRfcGVybWlzc2lvbnMiOnsicHViIjp7fSwic3ViIjp7fX0sImF1dGhvcml6YXRpb24iOnt9LCJ0eXBlIjoiYWNjb3VudCIsInZlcnNpb24iOjJ9fQ.hVi5gxo5Y2xus6je2lUmvXCq3PtCx_O0_B-7y-z40PrFTJhFCtehTW_lwxfJfXwauGHyMMqDQxC9YraUEQJ5DQ"
}
